### ISSUE TITLE
连续点击发送礼物会出现显示错误问题

### ISSUE THREAD

**Issue by WineKai** [baiyidjp/JPGiftManager#2]
![image](https://user-images.githubusercontent.com/16148218/41222990-1e6a0930-6d9b-11e8-94e9-406900a8a003.png)
为了方便测试，我把giftMaxNum修改为10。然后快速连续点击发送礼物，会出现如上问题。偶尔还会出现X11的礼物。

**Comment by WineKai** [comment]
![image](https://user-images.githubusercontent.com/16148218/41223075-5ae776e0-6d9b-11e8-9300-f44c11be009b.png)

**Comment by baiyidjp** [comment]
已修复
