### ISSUE TITLE
连发问题

### ISSUE THREAD

**Issue by mxpasser** [baiyidjp/JPGiftManager#4]
@baiyidjp 你好，有幸使用这个库，感谢。
有个问题想请教一下，就是我们应用里有连发和单发的礼物，连发时显示xN的数字，单发的礼物即使同一个人点击了同一个礼物仍然需要显示为x1，连发好说，单发时需要如何处理，谢谢

**Comment by baiyidjp** [comment]
> @baiyidjp 你好，有幸使用这个库，感谢。
> 有个问题想请教一下，就是我们应用里有连发和单发的礼物，连发时显示xN的数字，单发的礼物即使同一个人点击了同一个礼物仍然需要显示为x1，连发好说，单发时需要如何处理，谢谢

我的这个里面的区别是不是同一个礼物的关键点是 giftKey,所以只要不是同一个key,就不会连发,你可以想想,忙过这段时间我在看看吧

**Comment by mxpasser** [comment]
> > @baiyidjp 你好，有幸使用这个库，感谢。
> > 有个问题想请教一下，就是我们应用里有连发和单发的礼物，连发时显示xN的数字，单发的礼物即使同一个人点击了同一个礼物仍然需要显示为x1，连发好说，单发时需要如何处理，谢谢
> 
> 我的这个里面的区别是不是同一个礼物的关键点是 giftKey,所以只要不是同一个key,就不会连发,你可以想想,忙过这段时间我在看看吧

好的，谢谢
